//@version=4
// 注意！本版本背景色为白色。如果你用黑色背景，请自行调整颜色

study("MA+EMA",overlay=true)
e1=ema(close,20)
c1=sma(close,20)
e2=ema(close,60)
c2=sma(close,60)
e3=ema(close,120)
c3=sma(close,120)

plot(e1,"ema20",color=bar_index % 2 == 0 ? color.gray: color.white)
plot(c1,"ma20",color=#D3D3D3)
plot(e2,"ema60",color=bar_index % 2 == 0 ? color.red: color.white)
plot(c2,"ma60",color=#FDBCB4)
plot(e3,"ema120",color=bar_index % 2 == 0 ? color.blue: color.white)
plot(c3,"ma120",color=#ADD8E6)

//DKJ
cond=barstate.islast
moveBar=input(0)
x20=input(20)+moveBar
x60=input(60)+moveBar
x120=input(120)+moveBar

// 如果把小海军蓝點放在收盘价
circle_color=color.navy
transp_value=25
plot(cond?close[20]:na,color=circle_color,linewidth=5,offset=-x20,style=plot.style_circles,transp=transp_value, show_last=1)
plot(cond?close[60]:na,color=circle_color,linewidth=5,offset=-x60,style=plot.style_circles,transp=transp_value, show_last=1)
plot(cond?close[120]:na,color=circle_color,linewidth=5,offset=-x120,style=plot.style_circles,transp=transp_value, show_last=1)

// 如果把小黄點放在最低價便於觀看，把//去掉，但把//添加到上面五行
// circle_color=color.yellow
// plot(cond?low[20]:na,color=circle_color,linewidth=5,offset=-x20,style=plot.style_circles,transp=0, show_last=1)
// plot(cond?low[60]:na,color=circle_color,linewidth=5,offset=-x60,style=plot.style_circles,transp=0, show_last=1)
// plot(cond?low[120]:na,color=circle_color,linewidth=5,offset=-x120,style=plot.style_circles,transp=0, show_last=1)

// 用label代替plot，修复K线回放或者高频实时K线时，连续画抵扣价小圆点的bug
// 使用时把下面所有行的//去掉，并且把上面从//DKJ开始的行一直到本行删掉
//cond=barstate.islast
//if cond
    //DKJ_20=label.new(bar_index[20], low[20])
    //label.set_style(DKJ_20,label.style_labelup)
    //label.set_size(DKJ_20,size.tiny)
    //label.set_color(DKJ_20,color.yellow)
    //label.delete(id=DKJ_20[1])
    
    //DKJ_60=label.new(bar_index[60], low[60])
    //label.set_style(DKJ_60,label.style_labelup)
    //label.set_size(DKJ_60,size.tiny)
    //label.set_color(DKJ_60,color.yellow)
    //label.delete(id=DKJ_60[1])
    
    //DKJ_120=label.new(bar_index[120], low[120])
    //label.set_style(DKJ_120,label.style_labelup)
    //label.set_size(DKJ_120,size.tiny)
    //label.set_color(DKJ_120,color.yellow)
    //label.delete(id=DKJ_120[1])
